//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Web.App_GlobalResources.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManager.Web.App_GlobalResources.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ kho.
        /// </summary>
        public static string FromWareHouse {
            get {
                return ResourceManager.GetString("FromWareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập / Xuất.
        /// </summary>
        public static string Menu_ImportAndExport {
            get {
                return ResourceManager.GetString("Menu_ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kho.
        /// </summary>
        public static string Menu_Inventory {
            get {
                return ResourceManager.GetString("Menu_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa.
        /// </summary>
        public static string Menu_Merchandise {
            get {
                return ResourceManager.GetString("Menu_Merchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử hàng hóa.
        /// </summary>
        public static string Menu_Merchandise_History {
            get {
                return ResourceManager.GetString("Menu_Merchandise_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hàng hóa.
        /// </summary>
        public static string Menu_Merchandise_List {
            get {
                return ResourceManager.GetString("Menu_Merchandise_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lắp ráp.
        /// </summary>
        public static string Menu_Merchandise_NewAssemble {
            get {
                return ResourceManager.GetString("Menu_Merchandise_NewAssemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử hàng hóa.
        /// </summary>
        public static string Menu_MerchandiseHistory {
            get {
                return ResourceManager.GetString("Menu_MerchandiseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        public static string Menu_Report {
            get {
                return ResourceManager.GetString("Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string Menu_Vendor {
            get {
                return ResourceManager.GetString("Menu_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho hàng.
        /// </summary>
        public static string Menu_Warehouse {
            get {
                return ResourceManager.GetString("Menu_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho.
        /// </summary>
        public static string Merchandise_HeaderInventory {
            get {
                return ResourceManager.GetString("Merchandise_HeaderInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng hóa.
        /// </summary>
        public static string Merchandise_HeaderName {
            get {
                return ResourceManager.GetString("Merchandise_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến kho.
        /// </summary>
        public static string ToWareHouse {
            get {
                return ResourceManager.GetString("ToWareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import-list.
        /// </summary>
        public static string Url_import_List {
            get {
                return ResourceManager.GetString("Url_import_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory.
        /// </summary>
        public static string Url_inventory {
            get {
                return ResourceManager.GetString("Url_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchandise-history.
        /// </summary>
        public static string Url_merchandise_History {
            get {
                return ResourceManager.GetString("Url_merchandise_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchandise-list.
        /// </summary>
        public static string Url_merchandise_list {
            get {
                return ResourceManager.GetString("Url_merchandise_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchandise-new.
        /// </summary>
        public static string Url_merchandise_New {
            get {
                return ResourceManager.GetString("Url_merchandise_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchandise-new-assemble.
        /// </summary>
        public static string Url_merchandise_NewAssemble {
            get {
                return ResourceManager.GetString("Url_merchandise_NewAssemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merchandise-history.
        /// </summary>
        public static string Url_merchandiseHistory {
            get {
                return ResourceManager.GetString("Url_merchandiseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor-list.
        /// </summary>
        public static string Url_vendor_list {
            get {
                return ResourceManager.GetString("Url_vendor_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warehouse-list.
        /// </summary>
        public static string Url_warehouse_list {
            get {
                return ResourceManager.GetString("Url_warehouse_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Vendor_HeaderAddress {
            get {
                return ResourceManager.GetString("Vendor_HeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên NCC.
        /// </summary>
        public static string Vendor_HeaderName {
            get {
                return ResourceManager.GetString("Vendor_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhà cung cấp.
        /// </summary>
        public static string Vendor_List {
            get {
                return ResourceManager.GetString("Vendor_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string Warehouse_Address {
            get {
                return ResourceManager.GetString("Warehouse_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách kho hàng.
        /// </summary>
        public static string Warehouse_List {
            get {
                return ResourceManager.GetString("Warehouse_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kho hàng.
        /// </summary>
        public static string Warehouse_Name {
            get {
                return ResourceManager.GetString("Warehouse_Name", resourceCulture);
            }
        }
    }
}
